version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: proyecto0again
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    environment:
      POSTGRES_USER: postgres  # 👈 Use explicit values
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: proyecto0again
      POSTGRES_HOST: db
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    command: >
      sh -c "/usr/local/bin/wait-for-it.sh db:5432 --timeout=30 -- alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: