# Use a Node.js image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Clean npm cache and install dependencies
RUN npm cache clean --force && \
    npm install --include=dev 

# Copy the rest of the frontend code
COPY frontend /app

# Expose the port used by Vite (match your config)
EXPOSE 8080  

# Command to run the development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]