"""empty message

Revision ID: d7667062684b
Revises: 1b65d076683d
Create Date: 2025-01-27 22:46:55.253654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7667062684b'
down_revision: Union[str, None] = '1b65d076683d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CATEGORIA',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_CATEGORIA_ID'), 'CATEGORIA', ['ID'], unique=False)
    op.create_table('USUARIO',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', sa.String(length=255), nullable=False),
    sa.Column('contrasenia', sa.String(length=255), nullable=False),
    sa.Column('imagen_perfil', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_USUARIO_ID'), 'USUARIO', ['ID'], unique=False)
    op.create_index(op.f('ix_USUARIO_email'), 'USUARIO', ['email'], unique=True)
    op.create_table('TAREA',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('texto_tarea', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('fecha_tentativa_finalizacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('ID_Usuario', sa.Integer(), nullable=False),
    sa.Column('ID_Categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ID_Categoria'], ['CATEGORIA.ID'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ID_Usuario'], ['USUARIO.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_TAREA_ID'), 'TAREA', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TAREA_ID'), table_name='TAREA')
    op.drop_table('TAREA')
    op.drop_index(op.f('ix_USUARIO_email'), table_name='USUARIO')
    op.drop_index(op.f('ix_USUARIO_ID'), table_name='USUARIO')
    op.drop_table('USUARIO')
    op.drop_index(op.f('ix_CATEGORIA_ID'), table_name='CATEGORIA')
    op.drop_table('CATEGORIA')
    # ### end Alembic commands ###
